-- Add BANK_VERIFICATION to DocumentType enum
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BANK_VERIFICATION';

-- Add PENDING_RECORD_VALIDATION to TransactionStatus enum
ALTER TYPE "TransactionStatus" ADD VALUE IF NOT EXISTS 'PENDING_RECORD_VALIDATION';
