DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ActionType') THEN
    CREATE TYPE "ActionType" AS ENUM (
      'TRANSACTION_APPROVE',
      'TRANSACTION_REJECT',
      'DEPOSIT_CONFIRM',
      'DOCUMENT_APPROVE',
      'DOCUMENT_REJECT',
      'COMPLIANCE_REVIEW',
      'USER_SUSPEND',
      'USER_ACTIVATE',
      'LIMITS_OVERRIDE',
      'CASH_PICKUP_ISSUE',
      'PREPAID_CARD_ISSUE',
      'AGENT_CREATE',
      'AGENT_UPDATE_STATUS',
      'AGENT_APPROVE',
      'AGENT_DEACTIVATE',
      'RATE_CREATE',
      'RATE_UPDATE',
      'RATE_DEACTIVATE',
      'REPORT_GENERATE',
      'ADMIN_USER_CREATE',
      'ADMIN_USER_UPDATE',
      'ADMIN_USER_ACTIVATE',
      'ADMIN_USER_SUSPEND',
      'ROLE_CREATE',
      'ROLE_UPDATE',
      'ROLE_DELETE',
      'DEPARTMENT_CREATE',
      'DEPARTMENT_UPDATE',
      'DEPARTMENT_DELETE'
    );
  END IF;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TRANSACTION_APPROVE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TRANSACTION_REJECT';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DEPOSIT_CONFIRM';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DOCUMENT_APPROVE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DOCUMENT_REJECT';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'COMPLIANCE_REVIEW';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'USER_SUSPEND';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'USER_ACTIVATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'LIMITS_OVERRIDE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'CASH_PICKUP_ISSUE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'PREPAID_CARD_ISSUE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'AGENT_CREATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'AGENT_UPDATE_STATUS';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'AGENT_APPROVE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'AGENT_DEACTIVATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'RATE_CREATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'RATE_UPDATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'RATE_DEACTIVATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'REPORT_GENERATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_CREATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_UPDATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_ACTIVATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_SUSPEND';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ROLE_CREATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ROLE_UPDATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ROLE_DELETE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DEPARTMENT_CREATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DEPARTMENT_UPDATE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DEPARTMENT_DELETE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
