-- Add new admin-related action types to the existing Postgres enum "ActionType"
-- Safe to run multiple times due to IF NOT EXISTS
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_CREATE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_UPDATE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_ACTIVATE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ADMIN_USER_SUSPEND';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ROLE_CREATE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ROLE_UPDATE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'ROLE_DELETE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DEPARTMENT_CREATE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DEPARTMENT_UPDATE';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'DEPARTMENT_DELETE';
